[tool.poetry]
name = "learn-knn"
version = "0.1.0"
description = ""
authors = ["jonasliendl <57270170+jonasliendl@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
